# -*- coding: utf-8 -*-
"""DSB_kenya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyHdB8hmDPCqud-u0VkQtN4qS_o7tjv5
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = '/content/drive/MyDrive/dataset/DSB_Kenya_Cleaned_Dataset.xlsx'
df = pd.read_excel(path)
df.head(150)

df_filtered = df[df['Period'].isin([2017, 2018, 2019, 2020, 2021, 2022, 2023])]

print(df_filtered.describe())

partner_totals = df_filtered.groupby('Partner')['Value'].sum().reset_index()
print(partner_totals)

top_partners = partner_totals.nlargest(10, 'Value')
print(top_partners)

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(10, 5))
sns.barplot(data=top_partners, x='Value', y='Partner', palette='viridis')
plt.xlabel("Total Trade Value")
plt.ylabel("Trade Partner")
plt.title("Top 10 Trade Partners by Value")
plt.show()